name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Configuring environment
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.0

      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Run all openai-go tests
        run: go test ./...
